version: "3.1"

services:
  apache:
    build:
      context: ./apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    extra_hosts:
      - "${HOST}:127.0.0.1"
    hostname: ${HOST}
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    networks:
      public_net:
        ipv4_address: ${APACHE_IP}
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_LOG_DIR=${APACHE_LOG_DIR}
      - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
      - HOST=${HOST}
      - PHP_APP_DIR=${PHP_APP_DIR}
      - PHP_IP=${PHP_IP}
      - WEB_GROUP=${WEB_GROUP}
      - WEB_USER=${WEB_USER}
    volumes:
      - ../:/var/www/html
      - ../logs/docker/apache:${APACHE_LOG_DIR}
      - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    working_dir: /var/www/html
    restart: ${RESTART}

  php:
    build:
      context: ./php-fpm
      args:
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        - WEB_GROUP=${WEB_GROUP}
        - WEB_USER=${WEB_USER}
        - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
    container_name: ${COMPOSE_PROJECT_NAME}_php
    expose:
      - ${APACHE_EXPOSED_PORT}
      - 9003 # XDebug
    working_dir: ${PHP_APP_DIR}
    volumes:
      - ..:${PHP_APP_DIR}
      - ../logs/docker/php:${PHP_ROOT_DIR}/logs
      #- ../logs/docker/xdebug.log:/usr/local/etc/logs/xdebug.log
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./php-fpm/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
    depends_on:
      - apache
    networks:
      public_net:
        ipv4_address: ${PHP_IP}
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_IP=${APACHE_IP}
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - WEB_GROUP=${WEB_GROUP}
      - WEB_USER=${WEB_USER}
    restart: ${RESTART}

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
